### ISSUE TITLE
Support provisioning of SSO

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/realm-o-matic#1]
Create features to support login + provisioning of SSO for project team use.

Initial flow as discussed with Nick:
1. User login via IDIR
2. Fill in form for SSO realm request and submit
   - create database or
   - use GitHub issue with a template
   - exploring other solutions
3. Auto create sso realm
   - including sso-dev, sso-test, sso(prod, but disabled)
   - need to prevent duplicate requests for project
4. Approval request for production sso sent for review
   - Admin user for the system
   - may need version control of form if allowing content update (not mvp)
5. Approval given, enable sso prod

@kelpisland @nickmailhot Please provide inputs to the ticket.

**Comment by kelpisland** [comment]
I've **bolded** the features I think mage a good MVP - let's discuss:

**The user Must be valid IDIR user to request SSO realm**

**The user will Fills in form for SSO realm request and submit**
Client Onboarding Questionnaire 201811.docx

**The user will answer additional questions regarding the realm
Realm Name: (Note: lowercase, no special chars except -)
o	Contact/Admin of Realm:
o	ID Providers:
o	Product Owner: (this should already be in the client onboarding questionnaire)**

The user can delete/cancel a request at any time

The user can not submit multiple requests for the same repo/realm

**The user can not change the form after it has been approved.**

**The form should be visible and editable by the approvers.**

**Approval request sent to production sso team to review and make contact with submitter to review/plan any further actions.**

**Approval can login and click approve which will then provision prod.**

**Approval request for production sso sent for review**
need to prevent duplicate requests for project
Admin user for the system
may need version control of form if allowing content update (not mvp)
**Approval given, enable sso prod**
