### ISSUE TITLE
Investigate into Terraform KeyCloak provider

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/realm-o-matic#12]

**Comment by stewartshea** [comment]
https://mrparkers.github.io/terraform-provider-keycloak/

**Comment by stewartshea** [comment]
I'll put some time into this during the weekend and should have some results monday

**Comment by ShellyXueHan** [comment]
yea that one looks pretty good, they just recently got the idp part in which we will need.

**Comment by stewartshea** [comment]
Safe to close this for now, we've decided that TF isn't the way we want to go.
