### ISSUE TITLE
Explore and setup webhook

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/realm-o-matic#40]

**Comment by stewartshea** [comment]
The webhook will do exactly what we want; using this code 
- [webhook code](https://github.com/adnanh/webhook)

**Comment by stewartshea** [comment]
I'm currently working on one more layer of filtering in the webhook for security purposes and then this will be done

**Comment by stewartshea** [comment]
This has proven useful and exists for the status page, and the interaction with github example can be seen here: https://github.com/BCDevOps/platform-services/tree/master/tools/bots/ansible-webhook

closing out this card.

**Comment by stewartshea** [comment]
Ahh... I can't close this one, maybe @ShellyXueHan  can close :)
